# Generated by Django 4.0.4 on 2022-06-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
